RecipesProject/RecipesProject/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RecipesMVC.Entities;
using RecipesMVC.ModelsDto;
using RecipesMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecipesMVC.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        [HttpGet]
        // GET: CategoryController
        public ActionResult Index()
        {
            var categories = _service.GetAll();
            return View(categories);
        }
        
        [AllowAnonymous]
        [HttpGet]
        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var category = _service.GetById(id);
            return View(category);
        }

        // GET: CategoryController/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] CategoryDto model)
        {

            _service.Create(model.Name);
            return RedirectToAction(nameof(Index));

        }

        // GET: CategoryController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = _service.GetById(id);
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [FromForm] CategoryDto model)
        {

            _service.Update(id, model);
            return RedirectToAction(nameof(Index));
            //  return RedirectToAction(nameof(Edit),new { id = id });

        }

        // GET: CategoryController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {

            var category = _service.GetById(id);
            return View(category);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, [FromForm] CategoryDto category)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

RecipesProject/RecipesProject/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipesMVC.Entities;
using RecipesMVC.ModelsDto;
using RecipesMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace RecipesProject.Controllers
{
    [Authorize]
    public class RecipeController : Controller
    {
        private readonly IRecipeService _service;

        public RecipeController(IRecipeService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        [HttpGet]
        // GET: RecipeController
        public ActionResult Index()
        {
            var recipes = _service.GetAll();
            return View(recipes);
        }

        [AllowAnonymous]
        [HttpGet]
        // GET: RecipeController/Details/5
        public ActionResult Details(int id)
        {
            var recipe = _service.GetById(id);
            return View(recipe);
        }
        // GET: RecipeController/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecipeController/Create
        [HttpPost]
        public ActionResult Create([FromForm] RecipeDto model)
        {

            _service.Create(model);
            return RedirectToAction(nameof(Index));

        }

        // GET: RecipeController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = _service.GetById(id);
            return View(category);
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [FromForm] RecipeDto model)
        {

            _service.Update(id, model);
            return RedirectToAction(nameof(Index));
            //  return RedirectToAction(nameof(Edit),new { id = id });

        }

        // GET: RecipeController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {

            var category = _service.GetById(id);
            return View(category);
        }

        // POST: RecipeController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, [FromForm] CategoryDto category)
        {
            _service.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

RecipesProject/RecipesProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipesProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RecipesProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Recipe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RecipesProject - <a asp-area="" asp-controller="Account" asp-action="Register">Register</a> - <a asp-area="" asp-controller="Account" asp-action="Login">Login</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>